### ISSUE TITLE
[INVALID]<Failed Compile using Platform IO> with BugFix

### ISSUE THREAD

**Issue by agoy507** [luc-github/ESP3DLib#29]
**Describe the bug**
error compile.
Compiling .pio\build\esp32\lib3f5\ESP3DLib\web_server.cpp.o
.pio/libdeps/esp32/ESP3DLib/src/sd_ESP32.cpp: In member function 'bool ESP_SD::openDir(String)':
.pio/libdeps/esp32/ESP3DLib/src/sd_ESP32.cpp:324:32: error: 'class CardReader' has no member named 'getSd2Card'
     if (!sd_volume.init(&(card.getSd2Card()))) {
                                ^
Compiling .pio\build\esp32\lib3f5\ESP3DLib\wificonfig.cpp.o
At global scope:
cc1plus.exe: warning: unrecognized command line option '-Wno-register'
*** [.pio\build\esp32\lib3f5\ESP3DLib\sd_ESP32.cpp.o] Error 1.

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/77733757/114700828-33f98d00-9d4c-11eb-86a2-c65c61072a7e.png)
[Terminal Message.txt](https://github.com/luc-github/ESP3DLib/files/6310390/Terminal.Message.txt)
my configuration file
[Marlin-bugfix-2.0.x.zip](https://github.com/luc-github/ESP3DLib/files/6310399/Marlin-bugfix-2.0.x.zip)
Version
![image](https://user-images.githubusercontent.com/77733757/114701726-622b9c80-9d4d-11eb-8dbb-9abbdb3daa6e.png)

**Marlin Firmware:**
- Marlin bugfix lastest Version at april 14 2021 
- Any change done in Marlin code/configuration  

**ESP3DLib :**
- ESP3DLib Branch/Version:[e.g 2.1b14]  
- Web UI Version:[e.g 2.1b14]  
- Wifi mode:[e.g. STA]  
- Any change done in ESP3DLib code/configuration  

**Board used (please complete the following information):**
 - BOARD: [e.g. ESP32] 
 - Flash size: [e.g. 4M]
 - partitions: [e.g. default]

**Additional context**
wiring board https://github.com/felixstorm/Creality_Ender_3_ESP32_Board

**Comment by luc-github** [comment]
did you tested with 2.7.2 as mentioned in readme ?

**Comment by agoy507** [comment]
yes. I Was enable this feature followed in readme. so i attach file configuration. please tested to, and CMIIW.

**Comment by luc-github** [comment]
2.7.2 is ok
![image](https://user-images.githubusercontent.com/8822552/114706761-b15fd600-9d29-11eb-8dd8-c97b116405ae.png)

**Comment by agoy507** [comment]
Can you try test with marlin bugfix lastest version ?

**Comment by luc-github** [comment]
Marlin always break everything - and do not care backward compatibility - I will work on next release only - I have no bandwidth to test every change in Marlin and try to fix something that may be broken few commits later
Sorry
You are free to see what is wrong and push PR but in that case it may not work with 2.7.2

**Comment by agoy507** [comment]
ok. i will wait next release with your lib compability. thanks for your contribute.

**Comment by luc-github** [comment]
if homing in wrong direction it is just a Marlin setting - check the home direction setting

**Comment by agoy507** [comment]
OK. thanks for advice. i will check again marlin config. 
i think on bugfix marlin was fix my problem. cause the day before yesterday i was report this issue.

**Comment by luc-github** [comment]
@agoy507 motor direction and homing direction can be changed in Marlin FW that is for sure
if it is homing and moving which are up side down, it can also be changed also by just fliping the motor connector on board if it is possible but do it only when power off of you may damage driver

and for what it worst the change that generate your issue just happened few hours ago actually : https://github.com/MarlinFirmware/Marlin/commit/138340ee99a852bc116e2a436932bed074624fde
But I will only fix it when next release is out if I do now master will be incompatible with current 2.7.2 so need to wait as I do not want to maintain several branch and may be as mentioned code may change again before next release
