### ISSUE TITLE
Marlin 2.0.9.3 - No media error

### ISSUE THREAD

**Issue by ul42** [luc-github/ESP3DLib#43]
Bonjour à vous (désolé, je suis un peu fatigué ;) )

**Describe the bug**
Mon "plutôt handicapant" problème est que la carte Sd n'est absolument pas detectée.
Ni par Marlin, ni par ESP3D.

**To Reproduce**
Quand je clic sur "rafraichir", l'interface "SD" m'affiche un fichier nommé "OK" et qui ne sert apparament absolument a rien, et l'invite de commande me marque : "
echo:No media
ok
". Toute les actions depuis l'interface web me donne ces deux erreurs ainsi qu'un bug faisant reboot l'esp après de l'upload d'un gcode nommé "TstCube.gco".

**Expected behavior**
Je m'attend personellement a ce qu'il y ait un affichage, ainsi que pas de bug a l'upload d'un Gcode.

**Screenshots**
![ESP3d Problem 1](https://user-images.githubusercontent.com/85800590/166992562-4cf2a3dd-bfa5-45dd-b29e-5cc378e56501.PNG

**ESP3D Firmware:**
- ESP core version: non connue
- Version: non connue
- Web UI Version: 2.1b77
- Wifi mode: AP
- Flash method: PlatformIO
- Any change done in FW : Demander moi pour avoir les fichiers de config.
 
 tips: to get ESP3D informations type `[ESP420]plain`    
       to get WebUI version check your menu header    

**Target Firmware:**
 - Name: Marlin
 - Version: 2.0.9.3
 
 tip: to get firmware info type `M115` in console    
J'ai envoyé plusieures commandes tels que :

[ESP800]
FW version:2.0.9.3-1.0.11 # FW target:marlin-embedded  # FW HW:No SD # primary sd:/sd # secondary sd:none # authentication:no # webcommunication: Sync: 81:192.168.0.1# hostname:marlinesp(AP mode)

[ESP420]
Chip ID: 5152
CPU Frequency: 240Mhz
CPU Temperature: 71.1C
Free memory: 209.25 KB
SDK: v3.2.3-14-gd3e562907
Flash Size: 4.00 MB
Available Size for update: 1.81 MB
Available Size for SPIFFS: 287.03 KB
Baud rate: 250000
Sleep mode: None
Web port: 80
Hostname: marlinesp
Active Mode: AP (30:C6:F7:05:20:15)
SSID: MARLIN_ESP
Visible: Yes
Authentication: WPA2
Max Connections: 4
DHCP Server: Started
IP: 192.168.0.1
Gateway: 0.0.0.0
Mask: 255.255.255.0
Connected clients: 1
34:6F:24:A3:E7:31 192.168.0.2
Disabled Mode: STA (30:C6:F7:05:20:14)
FW version: Marlin 2.0.9.3 (ESP3D:1.0.11)

**Board used (please complete the following information):**
 - MCU: ESP32S
 - Name: Similaire a une Fysetc E4
 - Flash size: 4M

**Additional context**
Je suis en train de concevoir une machine FDM controllé par un ESP32S de Ai-Thinker ;)
J'en viens à vous surtout par manque de temps.

J'ai essayer plusieurs solutions :
- reformaté la carte SD.
- vérifié les paramètres de ESP3d, ESP3d WebUI, et du FW.
- activé/désactivé certaines options dans le marlin (voir les fichiers de config).
- vérifié le noms des gcodes contenu dans la sd.
- vérifié les schematics des cartes que j'utilise (les design sont propriétaire a moi même).
- ... (J'ai du en oublié d'autre).

Je pense que le faite est que je ne suis pas encore bien familliarisé avec l'environement logicielle des ESP32 et de ESP3D. Pour Marlin3d, je ne suis pas a ma première machine.

Je vous remercie d'avance pour l'aide.
Cordialement.

**Comment by ul42** [comment]
Ok je note ça, se sera utile.

Voici ce que me renvois Pronterface :
Connecting...
Printer is now online.
echo:busy: processing
echo:busy: processing
echo:busy: processing
>>>M20
SENDING:M20
echo:No media
>>>M21
SENDING:M21
echo:No SD card
>>>M20
SENDING:M20
echo:No media

Je vais changer quelques paramètres et je vous recontacte.

**Comment by luc-github** [comment]
Ben deja :
`echo:busy: processing`
si aucune commande n'est envoye ce n'est pas normal je pense

le No media  / No SD Card montre bien que Marlin ne voit pas la carte SD 
Quel est le pinout utilise pour la carte SD ?

**Comment by ul42** [comment]
J'ai activé le paramètre :
#define SD_SPI_SPEED SPI_EIGHTH_SPEED

Et ça me donne ça :
![ESP3d Problem 2](https://user-images.githubusercontent.com/85800590/167103317-ab6d5cf0-159c-4543-9adc-cc97d83f97b1.PNG)

J'ai également vérifié les brochages physique (ou cas ou) et tout est correctement relié a l'ESP32S.
Voici les brochages logiciels et un peu de doc en plus :
#define SD_MOSI_PIN                           23
#define SD_MISO_PIN                           19
#define SD_SCK_PIN                            18
#define SDSS                                   5
![ESP3d Problem 3](https://user-images.githubusercontent.com/85800590/167104322-d74d8629-399a-4e88-bcc8-e05598a91cb1.PNG)
![ESP3d Problem 4](https://user-images.githubusercontent.com/85800590/167104354-e9732ff4-216c-4d7c-a7a4-bc5dbf3515bd.PNG)

**Comment by luc-github** [comment]
Je vous conseille de tester 
1 - https://github.com/espressif/arduino-esp32/tree/master/libraries/SD
2 - de voir si ce reader qui me semble utiliser le pinout MMC est vraiment compatible SPI, et de tester avec un autre reader

**Comment by ul42** [comment]
Je vais essayer la librairie que vous me conseiller ;)
Par contre pour ce qui est du pinout MMC, c'est bien le SPI que j'utilise. C'est le même que celui de la Fysetc E4 qui est aussi en SPI et sinon il y aurait usage des broches data dans un ordre de priorité précis me semble t'il. Corriger moi si je raconte une bêtise.

**Comment by luc-github** [comment]
ce qu'il faut utiliser c'est https://github.com/espressif/arduino-esp32/blob/master/libraries/SD/examples/SD_Test/SD_Test.ino
il n'y a rien a modifier il fonctionne avec le  pinout sd par default

**Comment by ul42** [comment]
Comment dois-je faire pour l'utilliser ?

**Comment by ul42** [comment]
Bonjour à vous,
J'ai changé de carte SD, et tout est en fonction.
Je pense que ça doit être le formatage, que je pensais avoir réglé.

Le problème vient de moi.
Je vous remercie malgré tout pour l'aide.
Cordialement.

**Comment by luc-github** [comment]
Pour les cartes SD toujours utiliser des 4GB   et les formater avec https://www.sdcard.org/downloads/formatter/

**Comment by luc-github** [comment]
Bon devt de carte
