### ISSUE TITLE
[BUG]failed compilation on ESP401.cpp

### ISSUE THREAD

**Issue by nikybiasion** [luc-github/ESP3DLib#46]
**Describe the bug**
Compilation fail with error:
.pio/libdeps/mks_tinybee/ESP3DLib/src/core/espcmd/ESP401.cpp: In member function 'bool Commands::ESP401(const char*, level_authenticate_type, ESP3DOutput*)':
.pio/libdeps/mks_tinybee/ESP3DLib/src/core/espcmd/ESP401.cpp:89:34: error: ambiguous overload for 'operator=' (operand types are 'String' and 'bool')
                         response = false;
                                  ^

**To Reproduce**
1. pio build

**Marlin Firmware:**
- Marlin Branch/Version: 2.0.x MKS Tinybee

**ESP3DLib :**
- ESP3DLib Branch/Version: 3.0

**Comment by luc-github** [comment]
Are you sure you are using latest version ? - you may need to do a clear all in platformio/vscode to update latest ESP3DLib code
This issue has been fixed 3months ago :
![image](https://user-images.githubusercontent.com/8822552/184456184-4aa563f2-9c81-4c1c-a6d9-54cb0cbb3484.png)

And I have just tested compilation pass with AUTHENTICATION_FEATURE 
![image](https://user-images.githubusercontent.com/8822552/184456707-9a567768-52d9-4095-bb93-b7060bd3cb2d.png)

Be aware if you update code now you will get several updates and some need also the webUI to be updated, so you will have to update the webUI V3 also

**Comment by luc-github** [comment]
@nikybiasion let me know if a clear all - fix your issue , so this ticket can be closed

**Comment by nikybiasion** [comment]
ok, i've tried to build mks original firmware with esp3dlib3.0, but it fail. With your Marlin branch everything works fine

**Comment by luc-github** [comment]
yes Marlin need several changes, not yet implemented

**Comment by luc-github** [comment]
I close issue then
