### ISSUE TITLE
Hi Luc. I have tried ESP3dLib v3.0 on my custom Board. But file gcode and the folder in which there is a gcode file not showing but if I check directly on the printer. gcode files and folders containing gcode files exist.

### ISSUE THREAD

**Issue by luc-github** [luc-github/ESP3DLib#48]
Hi Luc. I have tried ESP3dLib v3.0 on my custom Board. But file gcode and the folder in which there is a gcode file not showing but if I check directly on the printer. gcode files and folders containing gcode files exist.

and controller fan for cooling main board  when stepper or heater on can't function.
when i used esp3dlib v1 with marlin 2.0.9 not happen problem.
 
![1](https://user-images.githubusercontent.com/77733757/199747636-a704044f-4702-4379-814d-bc0e70650c1a.png)
![2](https://user-images.githubusercontent.com/77733757/199747656-bb1f1057-a15e-47d9-b2c3-9a413cec744e.png)
![3](https://user-images.githubusercontent.com/77733757/199747658-3f0db4ae-a334-4853-8682-7f01412b1e51.png)
![4](https://user-images.githubusercontent.com/77733757/199747661-e4624f19-8dee-4989-8b64-22db0f0ccc1d.png)
![IMG_20221103_212113](https://user-images.githubusercontent.com/77733757/199747666-50e93c58-be39-433d-a500-53adb66ef07b.jpg)
![IMG_20221103_212129](https://user-images.githubusercontent.com/77733757/199747672-aae3346f-1b71-4142-987d-6ac2425e9fed.jpg)
![IMG_20221103_212142](https://user-images.githubusercontent.com/77733757/199747691-644173b7-dcd3-41fb-8e89-c6e9b23cbd9f.jpg)

_Originally posted by @agoy507 in https://github.com/luc-github/ESP3DLib/issues/39#issuecomment-1302203984_

**Comment by luc-github** [comment]
> controller fan for cooling main board when stepper or heater on can't function.

I do not know your board specs but ESP3DLib does not do anything  with these things check with latest Marlin to see if it is working - may be some configuration /code change - my fork is base on Marlin 2.1

>file gcode and the folder in which there is a gcode file

I see it can list some of content of SD card but not all ? is that correct ?
if Yes what is your SD card capacity ? did you try with another one ? is that formated with  https://www.sdcard.org/downloads/formatter/ ?

**Comment by luc-github** [comment]
@agoy507 please continue here

**Comment by agoy507** [comment]
Thanks Luc 
I finally got it working!!!!
I follow your advise for formated SDcard with https://www.sdcard.org/downloads/formatter/ ?

**Comment by luc-github** [comment]
what do you mean ?

**Comment by agoy507** [comment]
I have tried to send notification via telegram, but the message failed to send.  what's wrong?  if via LINE there is no problem.

**Comment by luc-github** [comment]
it may be config - did you followed the wiki ?

**Comment by agoy507** [comment]
Yes, i follow instruction the wiki.  I filled T1 with telegram token, T2 with channel name, I also tried to fill T2 with botname like  https://github.com/luc-github/ESP3D/issues/578 but still can't work. Any suggestion ?

**Comment by luc-github** [comment]
test your settings using your browser
`https://api.telegram.org/bot<your bot token>/sendMessage?chat_id=@<your configured chat room>&text=Hi`

**Comment by luc-github** [comment]
@agoy507 did you solved your Issue?

**Comment by agoy507** [comment]
hi luc. I'm sorry just update. yesterday i'm busy with my work.

yes i have solved the problem. i forgot to delete "<>" on bot token. thank you for sugestion.
your project very amazing.

now my problem just controller fan not function. now i still collect reference.

**Comment by luc-github** [comment]
Ok cool, I am closing issue then
Thank you for the kind words ^_^
