### ISSUE TITLE
Some help needed on how to install the WEB interface. 

### ISSUE THREAD

**Issue by JazzinSA** [luc-github/ESP3DLib#72]
I managed to get a clean compile without any errors or warnings. However, when booting the machine, I can log onto the machine and I get the landing page but cannot find the upload option to install the ESP3D Web UI like with version 1.0. Would love some pointers here.  of how to proceed.

**Comment by luc-github** [comment]
can you share the screenshot of the page you get ?

**Comment by JazzinSA** [comment]
![image](https://github.com/luc-github/ESP3DLib/assets/20857331/f3a39214-2c24-44af-bf5d-35627f6c17c1)

**Comment by luc-github** [comment]
here
<img width="512" alt="image" src="https://github.com/luc-github/ESP3DLib/assets/8822552/1913a3f0-80d4-4012-b9bb-b231c692a71c">

**Comment by luc-github** [comment]
and the file is this one : https://github.com/luc-github/ESP3D-WEBUI/tree/3.0/dist/Printer3D/Marlin-embedded

**Comment by JazzinSA** [comment]
Sorted, Thank you,
