### ISSUE TITLE
Compilation Error for POLAR 3D PRINTER in Marlin-ESP3DLib-V3-bugfix-2.1.x

### ISSUE THREAD

**Issue by Gokuh1980** [luc-github/ESP3DLib#77]
**Describe the bug**
When i setup Vscode to compile for FYSETC E4 a polar 3d Printer it aborts due to several warnings
I Have a NODEMCU ESP32S but they have the same pins so i used FYSETC E4

![image](https://github.com/luc-github/ESP3DLib/assets/5133989/4658dccb-1d9f-4c1d-961c-f3c9b46f4bff)

![image](https://github.com/luc-github/ESP3DLib/assets/5133989/25f4b721-ddf4-417d-bbeb-3bfb178e4fe3)

**Marlin Firmware:**
- Marlin Branch/Version:[e.g bugfix-2.1.x] 
- Kinetamits changed to POLAR  

**ESP3DLib :**
- ESP3DLib Branch/Version: 3  
-  
- Wifi mode:AP
 - BOARD: ESP32 FYSETC 4 
 - Flash size: 16M

**Comment by luc-github** [comment]
What Marlin repository are you using ? And what branch ?

**Comment by Gokuh1980** [comment]
Hi! thanks for your response!

https://github.com/luc-github/Marlin/tree/ESP3DLib-V3-bugfix-2.1.x
![image](https://github.com/luc-github/ESP3DLib/assets/5133989/786a4414-1e6f-4a9d-8654-fcdc9e909274)

**Comment by luc-github** [comment]
the issue is not linked to ESP3DLib
check if you have same issue with latest Marlin Buxfix 2.1 without enabling wifi because upstream is broken

**Comment by luc-github** [comment]
@Gokuh1980 any update ? can you compile with Upstream Marlin ?

**Comment by Gokuh1980** [comment]
Hi! Yes, i tried to compile the bugfix from marlin today and it fails with similar errors.

**Comment by luc-github** [comment]
does latest release having same issue ? https://github.com/MarlinFirmware/Marlin/releases/tag/2.1.2.1

**Comment by Gokuh1980** [comment]
Yes, i've tried it and it compiles ok, but that release doesn't have the polar geometry i'm trying to build.

Algo i really really like your work with esp3d and wifi.

So i think i will wait a little longer.

(I'm no so good at coding)

**Comment by luc-github** [comment]
ho then I suggest you to push issue in Marlin and follow resolution - then update here when fixed - I will then update the fork

**Comment by Gokuh1980** [comment]
Yes of course!!! Thank you!!! Keep up with your project, its fantastic!

**Comment by luc-github** [comment]
Thank you - sorry I have no bandwidth to follow all Marlin update so your help is really appreciate

**Comment by luc-github** [comment]
no but my fork was not up to date - I have just did a rebase from bugfix now- so you can give a try 
Be noted the fix you mention is not present yet so you need to apply it manually

**Comment by luc-github** [comment]
the warnings are normal and harmless

The config you provided is for ESP32 not FYSETC_E4 you must use FYSETC_E4  board if this is what you have

In both case ESP32 / FYSETC_E4 I cannot duplicate using your files 

![image](https://github.com/luc-github/ESP3DLib/assets/8822552/e6454801-c1ca-401a-a830-01e59beaccc1)

**Comment by luc-github** [comment]
@Gokuh1980 any update ?

**Comment by Gokuh1980** [comment]
hi Luc! i'm trying to compile in another computer at home with ubuntu but keep getting this error...


![image](https://github.com/luc-github/ESP3DLib/assets/5133989/cc563bec-64f7-4e4a-8a0d-988f29301e1a)

strange is that i don't have any display configured...  

[Marlin.zip](https://github.com/luc-github/ESP3DLib/files/13998231/Marlin.zip)

**Comment by luc-github** [comment]
>strange is that i don't have any display configured...

Really ?

But your configuration.h has :

#define MKS_MINI_12864_V3

and 
#define LCD_INFO_SCREEN_STYLE 0

and I just did a simple windiff with my repo

**Comment by luc-github** [comment]
sorry Idea for what? I do not understand the quuestion

**Comment by Gokuh1980** [comment]
i was having an error on upload because fysetc_e4 as a flash of 16mb and my board has 4mb, so it results in a bootloop. thats why i wanted to ask you if you have some testing compiling for a 4mb esp32. 

now i have changed esp32.csv partition file and it boots:

![image](https://github.com/luc-github/ESP3DLib/assets/5133989/ed575c71-c72d-4f07-95b1-1e56a2d8f242)

now i have to resolve the errors in the boot log.

**Comment by luc-github** [comment]
you just need to edit the env and adjust board size and use proper partition like min-spiffs one
